cypress/integration/businessServiceList.test.js
Adding e2e test for sorting business services.
=> Business services: test sorting

.github/scripts/issue_create.sh, .github/scripts/issue_transaction.sh, .github/workflows/issues.yml, .gitignore
=> Added GH workflow to sync issues

entrypoint.sh, nginx.conf.template
resolve #9 
resolve https://github.com/konveyor/tackle-application-inventory/issues/2
=> Add application-inventory to api proxy nginx conf

.github/workflows/ci-actions.yml, .storybook/theme.js, cypress.json, docker-compose.yml, konveyor-realm.json, src/setupProxy.js
Resolves: https://github.com/konveyor/tackle-ui/issues/12
Adding 'Application inventory' to gh workflow and to docker-compose.yml configuration
=> [tackle-ui#13] Add 'application-inventory' to the Github and development workflow

cypress/integration/application-inventory/applicationInventoryList.test.js, src/api/rest.tsx, src/pages/application-inventory/application-inventory.tsx, src/pages/application-inventory/components/remote-business-service/index.ts, src/pages/application-inventory/components/remote-business-service/remote-business-service.tsx
Resolves https://github.com/konveyor/tackle-ui/issues/12
=> [TACKLE-8] Create 'application inventory' page - add business service column

src/api/rest.tsx
resolve #35 
depends on https://github.com/konveyor/tackle-controls/pull/63
=> TACKLE-67 Stakeholder: job function filtering and sorting

src/api/rest.tsx, src/shared/hooks/useFetchBusinessServices/useFetchBusinessServices.test.tsx, src/shared/hooks/useFetchBusinessServices/useFetchBusinessServices.ts, src/shared/hooks/useFetchJobFunctions/useFetchJobFunctions.test.tsx, src/shared/hooks/useFetchJobFunctions/useFetchJobFunctions.ts, src/shared/hooks/useFetchStakeholderGroups/useFetchStakeholderGroups.test.tsx, src/shared/hooks/useFetchStakeholderGroups/useFetchStakeholderGroups.ts, src/shared/hooks/useFetchStakeholders/useFetchStakeholders.test.tsx, src/shared/hooks/useFetchStakeholders/useFetchStakeholders.ts
=> TACKLE-66 Apply sorting to values in dropdown menus

.github/workflows/ci-actions.yml, .github/workflows/test-containers.yml
Resolves: https://github.com/konveyor/tackle-ui/issues/29
=> Add --pull option to Publish-Docker-Github-Action action

src/Routes.tsx
Resolves https://github.com/konveyor/tackle-ui/issues/32
=> [TACKLE-8] application list must be the entry point for tackle UI

src/pages/application-inventory/components/application-form/application-form.tsx
Resolves https://github.com/konveyor/tackle-ui/issues/55
=> Remove dupplicate of form labels

.github/workflows/ci-actions.yml
Resolves https://github.com/konveyor/tackle-ui/issues/53
=> Remove job dependency

.github/dependabot.yml
Resolves: https://github.com/konveyor/tackle-ui/issues/28
=> Add dependabot for managing versions of main dependencies

cypress/integration/application-inventory/applications/filtering_table.test.js, cypress/integration/controls/business-services/filtering_table.test.js, cypress/integration/controls/stakeholder-groups/filtering_table.test.js, cypress/integration/controls/stakeholders/filtering_table.test.js, src/api/rest.tsx, src/pages/application-inventory/application-inventory.tsx, src/pages/application-inventory/components/toolbar-search-filter/index.ts, src/pages/application-inventory/components/toolbar-search-filter/input-text-filter/index.ts, src/pages/application-inventory/components/toolbar-search-filter/input-text-filter/input-text-filter.tsx, src/pages/application-inventory/components/toolbar-search-filter/select-business-service-filter/index.ts, src/pages/application-inventory/components/toolbar-search-filter/select-business-service-filter/select-business-service-filter.tsx, src/pages/application-inventory/components/toolbar-search-filter/toolbar-search-filter.tsx, src/pages/controls/business-services/business-services.tsx, src/pages/controls/stakeholder-groups/stakeholder-groups.tsx, src/pages/controls/stakeholders/stakeholders.tsx, src/shared/components/app-table-toolbar-toggle-group/app-table-toolbar-toggle-group.tsx, src/shared/components/simple-select/index.ts, src/shared/components/simple-select/simple-select.tsx, src/shared/hooks/useFetchApplications/useFetchApplications.ts
Resolves https://github.com/konveyor/tackle-ui/issues/51
This PR requires This PR requires https://github.com/konveyor/tackle-application-inventory/pull/14
=> [TACKLE-8] Application List: add filter by business service

src/api/rest.tsx
=> Switched to use '.size()' sorting query parameter

src/pages/application-inventory/components/toolbar-search-filter/select-business-service-filter/select-business-service-filter.tsx
Resolves https://github.com/konveyor/tackle-ui/issues/79
=> [TACKLE-8] Application List filter by business service not resetting text filter

public/locales/en/translation.json, public/locales/es/translation.json, src/pages/controls/business-services/components/business-service-form/business-service-form.tsx, src/pages/controls/tags/components/tag-form/tag-form.tsx, src/pages/controls/tags/components/tag-type-form/tag-type-form.tsx
=> Changed validations for business service, tag type and tag

src/pages/application-inventory/application-list/components/application-dependencies-form/application-dependencies-form.tsx
Resolves: https://github.com/konveyor/tackle-ui/issues/138
BEFORE:
AFTER:
=> Manage dependencies Form's fields are too close

cypress/integration/application-inventory/assessments/answer_questionnaire.test.js, cypress/integration/application-inventory/review/review.test.js, public/locales/en/translation.json, public/locales/es/translation.json, src/pages/application-inventory/application-assessment/application-assessment.tsx
Resolves: https://github.com/konveyor/tackle-ui/issues/168
https://issues.redhat.com/browse/TACKLE-171
=> [TACKLE-171] Next button enabled, even when stakeholder and stakeholdergroup not selected

src/pages/application-inventory/application-list/application-list.tsx, src/pages/application-inventory/application-list/components/application-tags/application-tags.tsx, src/pages/controls/business-services/business-services.tsx, src/pages/controls/job-functions/job-functions.tsx, src/pages/controls/stakeholder-groups/stakeholder-groups.tsx, src/pages/controls/stakeholders/stakeholders.tsx
Resolves: https://github.com/konveyor/tackle-ui/issues/165
https://issues.redhat.com/browse/TACKLE-178
=> [TACKLE-178] Lentghy names/description of application blocks all the other actions on application

src/pages/controls/tags/components/tag-form/tag-form.tsx, src/pages/controls/tags/components/tag-type-form/tag-type-form.tsx
Resolves: https://github.com/konveyor/tackle-ui/issues/161
https://issues.redhat.com/browse/TACKLE-153
=> [TACKLE-153] Tag name dropdown not visible for very long tag name

cypress/integration/controls/tags/create_new_tagtype_modal.test.js, src/pages/controls/tags/components/tag-type-form/tag-type-form.tsx
Resolves: https://github.com/konveyor/tackle-ui/issues/159
https://issues.redhat.com/browse/TACKLE-150
=> [TACKLE-150] Color is not mandatory while creating new tag type

src/pages/application-inventory/application-list/components/application-form/application-form.tsx, src/pages/application-inventory/application-review/components/review-form/review-form.tsx, src/pages/controls/business-services/components/business-service-form/business-service-form.tsx, src/pages/controls/job-functions/components/job-function-form/job-function-form.tsx, src/pages/controls/stakeholder-groups/components/stakeholder-group-form/stakeholder-group-form.tsx, src/pages/controls/stakeholders/components/stakeholder-form/stakeholder-form.tsx, src/pages/controls/tags/components/tag-form/tag-form.tsx, src/pages/controls/tags/components/tag-type-form/tag-type-form.tsx
Resolves: https://github.com/konveyor/tackle-ui/issues/163
https://issues.redhat.com/browse/TACKLE-154
=> [TACKLE 154] Able to create duplicate job functions with space in the end

src/pages/application-inventory/application-list/application-list.tsx, src/pages/controls/business-services/business-services.tsx, src/pages/controls/job-functions/job-functions.tsx, src/pages/controls/stakeholder-groups/stakeholder-groups.tsx, src/pages/controls/stakeholders/stakeholders.tsx, src/pages/controls/tags/tags.tsx, src/shared/hooks/useTableControls/useTableControls.test.tsx, src/shared/hooks/useTableControls/useTableControls.ts
Resolves: https://github.com/konveyor/tackle-ui/issues/172
https://issues.redhat.com/browse/TACKLE-155
=> [TACKLE-155] Pagination does not work with delete

public/locales/en/translation.json, public/locales/es/translation.json, src/pages/application-inventory/application-assessment/application-assessment.tsx, src/pages/application-inventory/application-assessment/components/application-assessment-page/__snapshots__/application-assessment-page-header.test.tsx.snap, src/pages/application-inventory/application-assessment/components/application-assessment-page/application-assessment-page-header.test.tsx, src/pages/application-inventory/application-assessment/components/application-assessment-page/application-assessment-page-header.tsx, src/shared/components/breadcrumb-path/breadcrumb-path.tsx, src/shared/components/breadcrumb-path/tests/breadcrumb-path.test.tsx, src/shared/components/page-header/page-header.tsx
Resolves: https://github.com/konveyor/tackle-ui/issues/170
https://issues.redhat.com/browse/TACKLE-175
=> [TACKLE-175] No user confirmation showed on clicking Cancel during assessment

src/pages/reports/components/identified-risks-table/identified-risks-table.tsx
=> Changed the risk filter label to be 'Application'

cypress/integration/template/about.test.js, src/layout/AppAboutModal/AppAboutModal.tsx, src/layout/AppAboutModal/tests/__snapshots__/AppAboutModal.test.tsx.snap
https://issues.redhat.com/browse/TACKLE-258
=> Add descrption to the About modal

src/pages/application-inventory/application-list/components/application-tags/application-tags.tsx
https://issues.redhat.com/browse/TACKLE-211
In order to fix the issue the UI will shown "Unknown" labels if the tag associated with the application doesn't exist anymore.
=> [TACKLE-211] - Deleting a tag associated with application inventory removes all the other tags

cypress/integration/application-inventory/applications/sorting_table.test.js, src/pages/application-inventory/application-list/application-list.tsx
https://issues.redhat.com/browse/TACKLE-264
=> [TACKLE-264]-Column name Tags should be updated to Tag count

INTERNATIONALIZATION.md, README.md, konveyor-realm.json
Add some instructions for contributors to be able to add a new language to Tackle UI
=> Add internationalization instructions

public/locales/en/translation.json, public/locales/es/translation.json, src/layout/AppAboutModal/AppAboutModal.tsx, src/layout/AppAboutModal/tests/__snapshots__/AppAboutModal.test.tsx.snap, src/shared/containers/application-dependencies-form/select-dependency.tsx
=> Add version to modal and translate dependencies dropdown
